const Menu = [
    {
        id : 1,
        name : "Masala Maggi",
        image : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC2lzlRU-Ij2l9Ifu395Pn7YRfalaE_PamNw&s",
        category: "Evening",
        price : "20",
        description:"A classic masala maggi.",
        type: "Veg",
    },
    {
        id : 2,
        name : "Pohe",
        image : "https://www.theloveofspice.com/wp-content/uploads/2019/01/kanda-poha-recipe.jpg",
        category: "Breakfast",
        price : "15",
        description:"Very Delicious Kanda Pohe From Maharashtra.",
        type: "Veg",
    },
    {
        id : 3,
        name : "Paneer Angara",
        image : "https://bongappetitcom.wordpress.com/wp-content/uploads/2021/09/wp-1630524459259.jpg?w=1200",
        category: "Lunch",
        price : "150",
        description:"With the flavor of Angara along with hot and spicy paneer.",
        type: "Veg",
    },
    {
        id : 4,
        name : "Pop Corn",
        image : "https://www.allrecipes.com/thmb/Q1qbaxGu71eF3tKyJ0wtmJfORRw=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/87305-microwave-popcorn-DDMFS-4x3-b4700cc9b5e440fd9d11eb0bdaf1395f.jpg",
        category: "Timepass",
        price : "10",
        description:"Crunchy and Cheesy delicious PopCorn",
        type: "Non-veg",
    },
    {
        id : 5,
        name : "Chicken Handi",
        image : "https://www.foodorderkar.com/wp-content/uploads/2021/07/images-2021-07-28T115233.980.jpeg",
        category: "Dinner",
        price : "200",
        description:"Hot and Fresh Chicken Handi with a great taste.",
        type: "Non-veg",
    },
    {
        id : 6,
        name : "Chicken Lollipop",
        image : "https://www.indianhealthyrecipes.com/wp-content/uploads/2015/07/chicken-lollipop-480x270.jpg",
        category: "Evening",
        price : "180",
        description:"Crispy and Spicy chicken lollipop.",
        type: "Non-veg",
    },
    {
        id : 7,
        name : "Upma",
        image : "https://myfoodstory.com/wp-content/uploads/2022/11/Vegetable-Upma-3-500x375.jpg",
        category: "Breakfast",
        price : "25",
        description:"Delicious upma with the taste of curry leaves.",
        type: "Veg",
    },
    {
        id : 8,
        name : "Bhendi Masala",
        image : "https://www.anveshan.farm/cdn/shop/articles/BhindiMasala.jpg?v=1690790485",
        category: "Lunch",
        price : "150",
        description:"Fresh and tasty with the fine blend of spices.",
        type: "Veg",
    },
    {
        id : 9,
        name : "Mutton Biryani",
        image : "https://www.masala.tv/wp-content/uploads/2021/05/mutton-biryanii.jpg",
        category: "Dinner",
        price : "190",
        description:"Fresh Mutton Biryani with delicious taste.",
        type: "Non-veg",
    },
    {
        id : 10,
        name : "Beingan Bharta",
        image : "https://www.indianhealthyrecipes.com/wp-content/uploads/2020/09/baingan-bharta-recipe.jpg",
        category: "Dinner",
        price : "130",
        description:"A fine roasted bengan bharta with bajra roti",
        type: "Veg",
    },
]
export default Menu;